name: Generate Snake Animation

on:
  workflow_dispatch:  # Allows you to manually trigger the action in the Actions tab
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Update to v3 to avoid deprecated node issues
      
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }} 
          output: "./output/github-contribution-grid-snake.svg"
 
